import Foundation

/// Which language the UI shows. `system` follows the Mac's language (Czech → Czech,
/// otherwise English). Kestrel ships its own lightweight table (no Xcode string catalog /
/// bundled `.lproj` needed, which the ad-hoc packaging can't produce). Anything not in the
/// table falls back to its English source string, so the UI is never blank.
/// Translate a source (English) string to the current UI language. Free function so any
/// view can localize without threading the model through — views re-render on language
/// change because their section (observing `AppModel`) republishes.
func L(_ en: String) -> String { Localization.translate(en, to: Localization.effective) }

enum AppLanguage: String, CaseIterable, Identifiable {
    case system, czech, english
    var id: String { rawValue }
    var label: String {
        switch self { case .system: return "System"; case .czech: return "Čeština"; case .english: return "English" }
    }
}

enum Localization {
    /// The user's setting (System/Čeština/English). Updated by `AppModel`. `effective`
    /// resolves `system` against the Mac's language.
    static var setting: AppLanguage = .system
    static var effective: AppLanguage {
        guard setting == .system else { return setting }
        return Locale.current.language.languageCode?.identifier == "cs" ? .czech : .english
    }

    static func translate(_ en: String, to lang: AppLanguage) -> String {
        guard lang == .czech else { return en }
        return cs[en] ?? en
    }

    /// English source → Czech. Covers the visible chrome (navigation, section headers,
    /// primary actions, verdicts). Extend as more of the deep UI gets localized.
    static let cs: [String: String] = Dictionary(csPairs, uniquingKeysWith: { first, _ in first })

    private static let csPairs: [(String, String)] = [
        // Sidebar + groups
        ("Smart Care", "Smart Care"),
        ("Dashboard", "Přehled"),
        ("Cleanup", "Úklid"),
        ("Space", "Místo"),
        ("Energy", "Energie"),
        ("Security", "Zabezpečení"),
        ("Applications", "Aplikace"),
        ("Permissions", "Oprávnění"),
        ("Tools", "Nástroje"),
        ("Assistant", "Asistent"),
        ("Activity", "Aktivita"),
        ("My Activity", "Moje aktivita"),
        ("Settings", "Nastavení"),
        ("Monitor", "Sledování"),
        ("Maintain", "Údržba"),
        ("Intelligence", "Inteligence"),
        ("Commands", "Příkazy"),
        // Section subtitles
        ("One honest pass across cleanup, protection and malware", "Jeden poctivý průchod: úklid, ochrana a malware"),
        ("Live health, storage forecast and protection at a glance", "Živý stav, předpověď místa a ochrana na první pohled"),
        ("Preview first — nothing is deleted, items move to the vault", "Nejdřív náhled — nic se nemaže, položky jdou do trezoru"),
        ("Where your storage is going", "Kam se ztrácí místo na disku"),
        ("What's using power — right now and over the last 24 hours", "Co spotřebovává energii — teď i za posledních 24 hodin"),
        ("Honest, evidence-based checks — no scare tactics", "Poctivé kontroly podložené důkazy — žádné strašení"),
        ("Uninstall cleanly (bundle + leftovers → vault) and see what has updates", "Čisté odinstalování (aplikace + zbytky → trezor) a přehled aktualizací"),
        ("Which apps hold Camera, Microphone, Full Disk Access and more — read-only", "Které aplikace mají kameru, mikrofon, plný přístup k disku a další — jen ke čtení"),
        ("One-click cleanup tools and developer utilities", "Nástroje na úklid jedním klikem a vývojářské utility"),
        ("What Kestrel has done, and how your Mac is doing — honest, from the audit log", "Co Kestrel udělal a jak se Macu daří — poctivě z auditního logu"),
        ("Preferences, the vault, and where Kestrel stores things", "Předvolby, trezor a kam Kestrel ukládá data"),
        // Dashboard / health
        ("Mac Health", "Stav Macu"),
        ("HEALTH", "STAV"),
        ("Free up space", "Uvolnit místo"),
        ("Run Smart Care", "Spustit Smart Care"),
        ("Get insight", "Získat postřeh"),
        ("Storage forecast", "Předpověď místa"),
        ("Protection", "Ochrana"),
        ("Great", "Skvělé"),
        ("Good", "Dobré"),
        ("Fair", "Ucházející"),
        ("Needs attention", "Vyžaduje pozornost"),
        ("Your Mac is in great shape", "Tvůj Mac je ve skvělé kondici"),
        ("Your Mac is running well", "Tvůj Mac šlape dobře"),
        ("A little upkeep would help", "Trocha údržby by pomohla"),
        ("Some things need attention", "Něco vyžaduje pozornost"),
        ("Disk", "Disk"),
        ("Memory", "Paměť"),
        ("CPU", "CPU"),
        ("Battery", "Baterie"),
        ("Network", "Síť"),
        ("free", "volných"),
        ("used", "využito"),
        ("cores", "jader"),
        ("/ day", "/ den"),
        ("Full in about", "Zaplní se asi za"),
        ("days at this rate", "dní při tomto tempu"),
        ("Freeing space overall — no fill date", "Celkově se místo uvolňuje — bez data zaplnění"),
        ("Building history", "Sbírám historii"),
        ("Kestrel records a daily snapshot. The forecast fills in after a couple of days.", "Kestrel dělá denní snímek. Předpověď se doplní po pár dnech."),
        ("Protected", "Chráněno"),
        ("Check protection", "Zkontroluj ochranu"),
        ("Gatekeeper on", "Gatekeeper zapnutý"),
        ("Gatekeeper assessments are off", "Gatekeeper kontroly jsou vypnuté"),
        ("Reading protection status…", "Načítám stav ochrany…"),
        ("Internet speed", "Rychlost internetu"),
        ("Measuring your connection…", "Měřím připojení…"),
        ("Measure download speed and latency", "Změř rychlost stahování a odezvu"),
        ("Testing…", "Testuji…"),
        ("Run test", "Spustit test"),
        ("Get one quick, honest AI insight about your storage and health.", "Získej rychlý poctivý AI postřeh o místě a stavu Macu."),
        ("Thinking…", "Přemýšlím…"),
        ("Refresh", "Obnovit"),
        ("metadata only · never file contents", "jen metadata · nikdy obsah souborů"),
        // Common actions / labels
        ("Scan", "Skenovat"),
        ("Rescan", "Znovu skenovat"),
        ("Clean", "Vyčistit"),
        ("Restore", "Obnovit"),
        ("Cancel", "Zrušit"),
        ("Choose…", "Vybrat…"),
        ("Review", "Zkontrolovat"),
        ("Review all", "Zkontrolovat vše"),
        ("Run", "Spustit"),
        ("Run again", "Spustit znovu"),
        ("Uninstall", "Odinstalovat"),
        ("Reset", "Resetovat"),
        ("Clear", "Vymazat"),
        ("Copy digest", "Kopírovat souhrn"),
        ("Get Mac Health", "Zjistit stav Macu"),
        ("Manage vault", "Spravovat trezor"),
        ("Open Security", "Otevřít Zabezpečení"),
        ("Open Privacy settings", "Otevřít nastavení soukromí"),
        ("Free up memory", "Uvolnit paměť"),
        ("Explain", "Vysvětlit"),
        ("Clean dev junk", "Vyčistit dev balast"),
        // Settings
        ("Preferences", "Předvolby"),
        ("Launch at login", "Spustit při přihlášení"),
        ("Start Kestrel automatically when you log in.", "Spustit Kestrel automaticky po přihlášení."),
        ("Low-space notifications", "Upozornění na málo místa"),
        ("A local alert when the disk is nearly full. Nothing leaves this Mac.", "Lokální upozornění, když je disk skoro plný. Nic neopustí tento Mac."),
        ("Vault retention", "Doba uchování v trezoru"),
        ("Language", "Jazyk"),
        ("Choose the interface language. System follows your Mac.", "Vyber jazyk rozhraní. Systém následuje nastavení Macu."),
        ("days", "dní"),
        ("How long cleaned items stay restorable before they can be purged.", "Jak dlouho zůstanou vyčištěné položky obnovitelné, než je lze trvale smazat."),
        ("Vault", "Trezor"),
        ("Safety", "Bezpečnost"),
        ("Version", "Verze"),
        // Smart Care (note: "Run Smart Care" is defined above in the Dashboard block)
        ("Smart Care complete", "Smart Care dokončeno"),
        ("Running Smart Care…", "Probíhá Smart Care…"),
        ("Reclaimable space", "Uvolnitelné místo"),
        ("macOS protection", "Ochrana macOS"),
        ("Downloads malware scan", "Sken malwaru ve Stažených"),
        ("Health", "Stav"),
        ("Malware", "Malware"),
        ("Waiting", "Čeká"),
        ("Scanning…", "Skenuji…"),
        ("Done", "Hotovo"),
        // Section headers / cards / states
        ("Draining right now", "Spotřeba právě teď"),
        ("Keeping the Mac awake", "Co brání uspání Macu"),
        ("Maintenance", "Údržba"),
        ("Measuring your Home folder…", "Měřím složku Home…"),
        ("Most draining — last 24 hours", "Největší spotřeba — 24 hodin"),
        ("My Tools", "Moje nástroje"),
        ("Network usage by app", "Síťový provoz podle aplikace"),
        ("No apps match", "Žádné aplikace neodpovídají"),
        ("No leaked credentials", "Žádné uniklé přihlašovací údaje"),
        ("Nothing to clean here", "Tady není co uklízet"),
        ("Nothing to remove", "Není co odstranit"),
        ("Nothing reclaimed yet", "Zatím nic uvolněno"),
        ("Orphaned launch agents", "Osiřelí launch agenti"),
        ("Reading privacy grants…", "Načítám oprávnění…"),
        ("Reading your applications…", "Načítám aplikace…"),
        ("Recommendations", "Doporučení"),
        ("Scan for threats", "Sken hrozeb"),
        ("Scan your Home folder", "Naskenovat složku Home"),
        ("Scanning for leaked secrets…", "Skenuji uniklé tajné údaje…"),
        ("Scanning for threats…", "Skenuji hrozby…"),
        ("Secrets scanner", "Skener tajných údajů"),
        ("Starts at login", "Spouští se při přihlášení"),
        ("Storage map", "Mapa místa"),
        ("Storage reclaimed", "Uvolněné místo"),
        ("Storage trend", "Trend místa"),
        ("System extensions", "Systémová rozšíření"),
        ("Try a different search.", "Zkus jiné hledání."),
        ("Updates available", "Dostupné aktualizace"),
        ("Vault is empty", "Trezor je prázdný"),
        ("By category", "Podle kategorie"),
        ("Scan for reclaimable space", "Hledat uvolnitelné místo"),
        ("or drop a folder anywhere here", "nebo sem přetáhni složku"),
        ("reclaimable", "uvolnitelných"),
        ("items", "položek"),
        ("Move to Vault", "Přesunout do trezoru"),
        ("AI second opinion", "AI druhý názor"),
        ("Uninstall selected", "Odinstalovat vybrané"),
        ("selected", "vybráno"),
        ("Search applications…", "Hledat aplikace…"),
        ("This category is already tidy in", "V této složce už je uklizeno:"),
        ("Nothing to restore — the vault copies were already gone.", "Není co obnovit — kopie v trezoru už tam nebyly."),
        // Energy
        ("Charging", "Nabíjí se"),
        ("On battery", "Na baterii"),
        ("About", "Asi"),
        ("until full", "do plného nabití"),
        ("remaining", "zbývá"),
        ("Health", "Kondice"),
        ("Cycles", "Cykly"),
        ("Temp", "Teplota"),
        ("Freeing…", "Uvolňuji…"),
        ("Free up memory", "Uvolnit paměť"),
        ("Runs macOS purge to free inactive memory — non-destructive", "Spustí macOS purge pro uvolnění neaktivní paměti — nedestruktivní"),
        ("of", "z"),
        ("App", "Aplikace"),
        ("Wired", "Rezervováno"),
        ("Compressed", "Komprimováno"),
        ("Free", "Volné"),
        ("Reading energy usage…", "Načítám spotřebu energie…"),
        ("Why is this using power?", "Proč to spotřebovává energii?"),
        ("Measuring per-app traffic…", "Měřím provoz podle aplikace…"),
        ("Cumulative traffic since each process started (via nettop). Read-only.", "Kumulativní provoz od spuštění procesu (přes nettop). Jen ke čtení."),
        ("Building history… this fills in while Kestrel is running.", "Sbírám historii… doplní se, dokud Kestrel běží."),
        ("Recorded since", "Zaznamenáno od"),
        ("Quit", "Ukončit"),
        ("This asks the app to quit (SIGTERM). Unsaved work in that app may be lost.", "Požádá aplikaci o ukončení (SIGTERM). Neuložená práce může být ztracena."),

        // Security
        ("macOS protection is on", "Ochrana macOS je zapnutá"),
        ("Protection needs a look", "Ochrana potřebuje pozornost"),
        ("Gatekeeper and XProtect are active.", "Gatekeeper a XProtect jsou aktivní."),
        ("One of macOS's built-in defenses is off.", "Jedna z vestavěných ochran macOS je vypnutá."),
        ("On", "Zap"),
        ("Off", "Vyp"),
        ("Unknown", "Neznámé"),
        ("Scan for malware", "Skenovat malware"),
        ("Reading files in", "Čtu soubory v"),
        ("No threats", "Bez hrozeb"),
        ("Scanned", "Naskenováno"),
        ("file(s) — no threats found. No scare tactics.", "souborů — žádné hrozby. Žádné strašení."),
        ("finding(s), each with evidence", "nálezů, každý s důkazem"),
        ("These agents point at programs that no longer exist — usually safe to remove.", "Tito agenti míří na programy, které už neexistují — obvykle bezpečné odstranit."),
        ("Came from the internet", "Staženo z internetu"),
        ("Files in Downloads still flagged by Gatekeeper (quarantine) — normal for anything you downloaded. The agent shows what fetched it.", "Soubory ve Stažených stále označené Gatekeeperem (karanténa) — normální u čehokoli staženého. Agent ukazuje, co je stáhlo."),

        // Tools
        ("Trash Bins", "Koše"),
        ("Empty every Trash — undoable via the vault", "Vysypat všechny koše — vratné přes trezor"),
        ("App Leftovers", "Zbytky aplikací"),
        ("Data left behind by removed apps", "Data po odstraněných aplikacích"),
        ("Old Installers", "Staré instalátory"),
        (".dmg / .pkg / .iso in Downloads", ".dmg / .pkg / .iso ve Stažených"),
        ("Screenshots", "Snímky obrazovky"),
        ("Screenshots on the Desktop", "Snímky obrazovky na ploše"),
        ("Downloads", "Stažené"),
        ("Files older than 30 days", "Soubory starší 30 dní"),
        ("Mail Attachments", "Přílohy e-mailů"),
        ("Locally cached, re-downloadable", "Lokální kopie, znovu stažitelné"),
        ("Similar Images", "Podobné obrázky"),
        ("Keep the best of each group", "Ponechat nejlepší z každé skupiny"),
        ("No launch agents found.", "Žádní launch agenti nenalezeni."),
        ("Launch agents that run when you log in. Ones pointing at a missing program are flagged.", "Launch agenti spouštění při přihlášení. Ti mířící na chybějící program jsou označeni."),
        ("Scan for leaked credentials", "Skenovat uniklé údaje"),
        ("Reading", "Čtu"),
        ("No API keys, tokens or private keys found in", "Žádné API klíče, tokeny ani privátní klíče v"),
        ("potential secret(s)", "možných tajných údajů"),
        ("Nothing is preventing sleep.", "Nic nebrání uspání."),
        ("Advisory — run these yourself; they change system state. Copy the command when you're ready.", "Doporučující — spusť sám; mění stav systému. Zkopíruj příkaz, až budeš připraven."),

        // Applications
        ("From Homebrew casks — advisory; Kestrel never updates silently.", "Z Homebrew casks — doporučující; Kestrel nikdy neaktualizuje potají."),
        ("app(s)", "aplikací"),
        ("apps", "aplikací"),
        ("Nothing was found to", "Nebylo co"),
        ("reset", "resetovat"),
        ("remove", "odstranit"),
        ("These", "Těchto"),
        ("item(s) —", "položek —"),
        ("— will move to the vault. Undoable.", "— se přesune do trezoru. Vratné."),
        ("Close", "Zavřít"),
        ("Select for batch uninstall", "Vybrat pro hromadné odinstalování"),
        ("Reveal in Finder", "Zobrazit ve Finderu"),

        // Permissions — TCC service friendly names
        ("Camera", "Kamera"),
        ("Microphone", "Mikrofon"),
        ("Full Disk Access", "Plný přístup k disku"),
        ("Desktop folder", "Složka Plocha"),
        ("Documents folder", "Složka Dokumenty"),
        ("Downloads folder", "Složka Stažené"),
        ("Network volumes", "Síťové svazky"),
        ("Removable volumes", "Vyměnitelné svazky"),
        ("Accessibility", "Zpřístupnění"),
        ("Input monitoring", "Sledování vstupu"),
        ("Screen recording", "Nahrávání obrazovky"),
        ("Automation", "Automatizace"),
        ("Photos", "Fotky"),
        ("Contacts", "Kontakty"),
        ("Calendar", "Kalendář"),
        ("Reminders", "Připomínky"),
        ("Location", "Poloha"),
        ("Media library", "Knihovna médií"),
        ("Speech recognition", "Rozpoznávání řeči"),

        // Permissions
        ("Per-user privacy grants, read-only from your TCC database. System-level ones like Full Disk Access and Accessibility live in a root-only database and may not all appear here — manage everything in System Settings.", "Oprávnění na úrovni uživatele, jen ke čtení z tvé TCC databáze. Systémová jako plný přístup k disku a zpřístupnění žijí v databázi jen pro root a nemusí se tu všechna zobrazit — spravuj vše v Nastavení systému."),
        ("No app permissions found", "Žádná oprávnění aplikací"),
        ("Full Disk Access needed", "Potřeba plný přístup k disku"),
        ("Nothing has requested a protected resource yet.", "Zatím nic nežádalo o chráněný zdroj."),
        ("Grant Kestrel Full Disk Access to read the privacy database.", "Udělte Kestrelu plný přístup k disku pro čtení databáze soukromí."),

        // Smart Care results
        ("Here's what it found — nothing was deleted.", "Tady je, co našel — nic nebylo smazáno."),
        ("Reclaimable space, macOS protection and a Downloads malware scan, in one honest pass.", "Uvolnitelné místo, ochrana macOS a sken malwaru ve Stažených — v jednom poctivém průchodu."),
        ("Check", "Zkontroluj"),
        ("Gatekeeper + XProtect active", "Gatekeeper + XProtect aktivní"),
        ("A defense is off", "Ochrana je vypnutá"),
        ("files", "souborů"),
        ("finding(s) with evidence", "nálezů s důkazem"),
        ("Nothing to reclaim", "Není co uvolnit"),
        ("Your Home folder is already tidy.", "Tvoje složka Home je už uklizená."),
        ("safe item(s) across caches, logs and dev artifacts.", "bezpečných položek napříč cache, logy a dev artefakty."),

        // Space
        ("Scan Home", "Naskenovat Home"),
        ("Rescan", "Znovu skenovat"),
        ("Reading top-level folders…", "Čtu složky nejvyšší úrovně…"),
        ("Sized by real on-disk usage (allocated bytes), so sparse files like Docker.raw show their true footprint. Click a block to drill in.", "Velikost podle reálného využití disku (alokované bajty), takže řídké soubory jako Docker.raw ukazují skutečnou stopu. Klikni na blok pro zanoření."),
        ("Used", "Využito"),
        ("Purgeable", "Uvolnitelné"),
        ("This reads Desktop, Documents, Downloads and Pictures, so macOS may ask for permission. Click Scan Home when you're ready.", "Čte Plochu, Dokumenty, Stažené a Obrázky, takže macOS může požádat o oprávnění. Klikni na Naskenovat Home, až budeš připraven."),

        // Full Disk Access banner
        ("Grant Full Disk Access", "Udělit plný přístup k disku"),
        ("Without it, macOS hides the Trash, Mail and some caches — so tools like “Empty Trash” find nothing. Turn Kestrel on in Settings, then relaunch.", "Bez něj macOS skryje Koš, Mail a některé cache — takže nástroje jako Vysypat koš nic nenajdou. Zapni Kestrel v Nastavení a spusť znovu."),
        ("Open Full Disk Access settings", "Otevřít nastavení plného přístupu k disku"),

        // Settings
        ("Audit log", "Auditní log"),
        ("Reveal ~/.kestrel in Finder", "Zobrazit ~/.kestrel ve Finderu"),
        ("Cleanups are dry-run by default. Nothing is deleted outright — items move to the vault and can be undone. Zero telemetry: nothing leaves this Mac.", "Úklidy jsou defaultně nanečisto. Nic se nemaže napřímo — položky jdou do trezoru a jdou vrátit. Nulová telemetrie: nic neopustí tento Mac."),
        ("session(s)", "relací"),
        ("Everything a cleanup removes is moved here first, so it can be restored. Purging is the only place data is really deleted.", "Vše, co úklid odstraní, jde nejdřív sem, aby to šlo obnovit. Protřídění je jediné místo, kde se data opravdu mažou."),
        ("Cleaned items will appear here, restorable until you purge.", "Vyčištěné položky se objeví tady, obnovitelné dokud je neprotřídíš."),
        ("Purge older than", "Protřídit starší než"),
        ("Restore", "Obnovit"),
        ("item(s)", "položek"),

        // Assistant
        ("Honest AI help · sends metadata only", "Poctivá AI pomoc · posílá jen metadata"),
        ("New chat", "Nový chat"),
        ("Ask me about your Mac's storage, or analyze a folder.", "Zeptej se na místo na Macu nebo nech analyzovat složku."),
        ("What's using most of my disk?", "Co mi zabírá nejvíc místa?"),
        ("Is it safe to clear developer caches?", "Je bezpečné smazat vývojářské cache?"),
        ("How can I free space as a developer?", "Jak jako vývojář uvolním místo?"),
        ("What are the biggest wins to reclaim space?", "Kde nejvíc uvolním místo?"),
        ("Choose a folder to analyze:", "Vyber složku k analýze:"),
        ("Analyze", "Analyzovat"),
        ("Ask anything…", "Zeptej se na cokoli…"),
        ("Turn on the assistant", "Zapnout asistenta"),
        ("The assistant is opt-in and off by default. To enable it, put your Google Gemini API key in a file:", "Asistent je volitelný a defaultně vypnutý. Zapneš ho vložením svého Google Gemini API klíče do souboru:"),
        ("It then sends only metadata (names, sizes, categories) — never file contents.", "Pak posílá jen metadata (názvy, velikosti, kategorie) — nikdy obsah souborů."),

        // Command palette
        ("Go to", "Přejít na"),
        ("Section", "Sekce"),
        ("Run speed test", "Spustit test rychlosti"),
        ("Ask the assistant", "Zeptat se asistenta"),
        ("Vault & logs", "Trezor a logy"),
        ("Search or run a command…", "Hledej nebo spusť příkaz…"),
        ("No matching commands.", "Žádné odpovídající příkazy."),
        ("run", "spustit"),
        ("dismiss", "zavřít"),
        ("command(s)", "příkazů"),

        // Menu-bar popover
        ("Everything looks healthy", "Vše vypadá zdravě"),
        ("A little attention needed", "Chce trochu pozornosti"),
        ("Dev junk, caches, duplicates & more", "Dev balast, cache, duplikáty a další"),
        ("Measuring…", "Měřím…"),
        ("Download & latency", "Stahování a odezva"),
        ("Open Kestrel", "Otevřít Kestrel"),

        // Categories
        ("CATEGORY", "KATEGORIE"),
        ("Everything safe", "Vše bezpečné"),
        ("Dev artifacts", "Dev artefakty"),
        ("Caches", "Cache"),
        ("Logs", "Logy"),
        ("Duplicates", "Duplikáty"),
        ("Large & old", "Velké a staré"),
        ("Privacy", "Soukromí"),    ]
}
