import Foundation

/// Which language the UI shows. `system` follows the Mac's language (Czech → Czech,
/// otherwise English). Kestrel ships its own lightweight table (no Xcode string catalog /
/// bundled `.lproj` needed, which the ad-hoc packaging can't produce). Anything not in the
/// table falls back to its English source string, so the UI is never blank.
/// Translate a source (English) string to the current UI language. Free function so any
/// view can localize without threading the model through — views re-render on language
/// change because their section (observing `AppModel`) republishes.
func L(_ en: String) -> String { Localization.translate(en, to: Localization.effective) }

enum AppLanguage: String, CaseIterable, Identifiable {
    case system, czech, english
    var id: String { rawValue }
    var label: String {
        switch self { case .system: return "System"; case .czech: return "Čeština"; case .english: return "English" }
    }
}

/// Which AI backend the assistant should use. `auto` prefers whatever's available, local first
/// (on-device → Ollama → Gemini); `local` forces on-device/Ollama; `gemini` forces the cloud.
enum AIBackend: String, CaseIterable, Identifiable {
    case auto, local, gemini
    var id: String { rawValue }
    var label: String {
        switch self {
        case .auto: return L("Automatic")
        case .local: return L("Local")
        case .gemini: return L("Gemini")
        }
    }
}

enum Localization {
    /// The user's setting (System/Čeština/English). Updated by `AppModel`. `effective`
    /// resolves `system` against the Mac's language.
    static var setting: AppLanguage = .system
    static var effective: AppLanguage {
        guard setting == .system else { return setting }
        return Locale.current.language.languageCode?.identifier == "cs" ? .czech : .english
    }

    static func translate(_ en: String, to lang: AppLanguage) -> String {
        guard lang == .czech else { return en }
        return cs[en] ?? en
    }

    /// English source → Czech. Covers the visible chrome (navigation, section headers,
    /// primary actions, verdicts). Extend as more of the deep UI gets localized.
    static let cs: [String: String] = Dictionary(csPairs, uniquingKeysWith: { first, _ in first })

    private static let csPairs: [(String, String)] = [
        // Sidebar + groups
        ("Smart Care", "Smart Care"),
        ("Dashboard", "Přehled"),
        ("Cleanup", "Úklid"),
        ("Space", "Místo"),
        ("Energy", "Energie"),
        ("Security", "Zabezpečení"),
        ("Applications", "Aplikace"),
        ("Permissions", "Oprávnění"),
        ("Tools", "Nástroje"),
        ("Assistant", "Asistent"),
        ("Activity", "Aktivita"),
        ("My Activity", "Moje aktivita"),
        ("Settings", "Nastavení"),
        ("Monitor", "Sledování"),
        ("Maintain", "Údržba"),
        ("Intelligence", "Inteligence"),
        ("Commands", "Příkazy"),
        // Section subtitles
        ("One honest pass across cleanup, protection and malware", "Jeden poctivý průchod: úklid, ochrana a malware"),
        ("Live health, storage forecast and protection at a glance", "Živý stav, předpověď místa a ochrana na první pohled"),
        ("Preview first — nothing is deleted, items move to the vault", "Nejdřív náhled — nic se nemaže, položky jdou do trezoru"),
        ("Where your storage is going", "Kam se ztrácí místo na disku"),
        ("What's using power — right now and over the last 24 hours", "Co spotřebovává energii — teď i za posledních 24 hodin"),
        ("Honest, evidence-based checks — no scare tactics", "Poctivé kontroly podložené důkazy — žádné strašení"),
        ("Uninstall cleanly (bundle + leftovers → vault) and see what has updates", "Čisté odinstalování (aplikace + zbytky → trezor) a přehled aktualizací"),
        ("Which apps hold Camera, Microphone, Full Disk Access and more — read-only", "Které aplikace mají kameru, mikrofon, plný přístup k disku a další — jen ke čtení"),
        ("One-click cleanup tools and developer utilities", "Nástroje na úklid jedním klikem a vývojářské utility"),
        ("What Kestrel has done, and how your Mac is doing — honest, from the audit log", "Co Kestrel udělal a jak se Macu daří — poctivě z auditního logu"),
        ("Preferences, the vault, and where Kestrel stores things", "Předvolby, trezor a kam Kestrel ukládá data"),
        // Dashboard / health
        ("Mac Health", "Stav Macu"),
        ("HEALTH", "STAV"),
        ("Free up space", "Uvolnit místo"),
        ("Run Smart Care", "Spustit Smart Care"),
        ("Get insight", "Získat postřeh"),
        ("Storage forecast", "Předpověď místa"),
        ("What grew", "Co narostlo"),
        ("d", "d"),
        ("Change over the last", "Změna za posledních"),
        ("days, from daily snapshots. All tracked folders are regeneratable.", "dní, z denních snímků. Všechny sledované složky jsou znovu-generovatelné."),
        ("Protection", "Ochrana"),
        ("Great", "Skvělé"),
        ("Good", "Dobré"),
        ("Fair", "Ucházející"),
        ("Needs attention", "Vyžaduje pozornost"),
        ("Your Mac is in great shape", "Tvůj Mac je ve skvělé kondici"),
        ("Your Mac is running well", "Tvůj Mac šlape dobře"),
        ("A little upkeep would help", "Trocha údržby by pomohla"),
        ("Some things need attention", "Něco vyžaduje pozornost"),
        ("Disk", "Disk"),
        ("Memory", "Paměť"),
        ("CPU", "CPU"),
        ("Battery", "Baterie"),
        ("Network", "Síť"),
        ("free", "volných"),
        ("used", "využito"),
        ("cores", "jader"),
        ("/ day", "/ den"),
        ("Full in about", "Zaplní se asi za"),
        ("days at this rate", "dní při tomto tempu"),
        ("Freeing space overall — no fill date", "Celkově se místo uvolňuje — bez data zaplnění"),
        ("Building history", "Sbírám historii"),
        ("Kestrel records a daily snapshot. The forecast fills in after a couple of days.", "Kestrel dělá denní snímek. Předpověď se doplní po pár dnech."),
        ("Protected", "Chráněno"),
        ("Check protection", "Zkontroluj ochranu"),
        ("Gatekeeper on", "Gatekeeper zapnutý"),
        ("Gatekeeper assessments are off", "Gatekeeper kontroly jsou vypnuté"),
        ("Reading protection status…", "Načítám stav ochrany…"),
        ("Internet speed", "Rychlost internetu"),
        ("Measuring your connection…", "Měřím připojení…"),
        ("Measure download speed and latency", "Změř rychlost stahování a odezvu"),
        ("Testing…", "Testuji…"),
        ("Run test", "Spustit test"),
        ("Get one quick, honest AI insight about your storage and health.", "Získej rychlý poctivý AI postřeh o místě a stavu Macu."),
        ("Thinking…", "Přemýšlím…"),
        ("Refresh", "Obnovit"),
        ("metadata only · never file contents", "jen metadata · nikdy obsah souborů"),
        // Common actions / labels
        ("Scan", "Skenovat"),
        ("Rescan", "Znovu skenovat"),
        ("Clean", "Vyčistit"),
        ("Restore", "Obnovit"),
        ("Cancel", "Zrušit"),
        ("Choose…", "Vybrat…"),
        ("Review", "Zkontrolovat"),
        ("Review all", "Zkontrolovat vše"),
        ("Run", "Spustit"),
        ("Run again", "Spustit znovu"),
        ("Uninstall", "Odinstalovat"),
        ("Reset", "Resetovat"),
        ("Clear", "Vymazat"),
        ("Copy digest", "Kopírovat souhrn"),
        ("Get Mac Health", "Zjistit stav Macu"),
        ("Manage vault", "Spravovat trezor"),
        ("Verify undo works", "Ověřit, že undo funguje"),
        ("Fire-drill passed —", "Test obnovy prošel —"),
        ("session(s), every item restorable.", "relací, každá položka obnovitelná."),
        ("session(s) have missing or altered vault data — see below.", "relací má chybějící nebo změněná data v trezoru — viz níže."),
        ("Open Security", "Otevřít Zabezpečení"),
        ("Open Privacy settings", "Otevřít nastavení soukromí"),
        ("Free up memory", "Uvolnit paměť"),
        ("Explain", "Vysvětlit"),
        ("Clean dev junk", "Vyčistit dev balast"),
        // Settings
        ("Preferences", "Předvolby"),
        ("Launch at login", "Spustit při přihlášení"),
        ("Start Kestrel automatically when you log in.", "Spustit Kestrel automaticky po přihlášení."),
        ("Low-space notifications", "Upozornění na málo místa"),
        ("A local alert when the disk is nearly full. Nothing leaves this Mac.", "Lokální upozornění, když je disk skoro plný. Nic neopustí tento Mac."),
        ("Vault retention", "Doba uchování v trezoru"),
        ("Language", "Jazyk"),
        ("Choose the interface language. System follows your Mac.", "Vyber jazyk rozhraní. Systém následuje nastavení Macu."),
        ("days", "dní"),
        ("How long cleaned items stay restorable before they can be purged.", "Jak dlouho zůstanou vyčištěné položky obnovitelné, než je lze trvale smazat."),
        ("Vault", "Trezor"),
        ("Safety", "Bezpečnost"),
        ("Version", "Verze"),
        // Smart Care (note: "Run Smart Care" is defined above in the Dashboard block)
        ("Smart Care complete", "Smart Care dokončeno"),
        ("Running Smart Care…", "Probíhá Smart Care…"),
        ("Reclaimable space", "Uvolnitelné místo"),
        ("macOS protection", "Ochrana macOS"),
        ("Downloads malware scan", "Sken malwaru ve Stažených"),
        ("Health", "Stav"),
        ("Malware", "Malware"),
        ("Waiting", "Čeká"),
        ("Scanning…", "Skenuji…"),
        ("Done", "Hotovo"),
        // Section headers / cards / states
        ("Draining right now", "Spotřeba právě teď"),
        ("Keeping the Mac awake", "Co brání uspání Macu"),
        ("Maintenance", "Údržba"),
        ("Measuring your Home folder…", "Měřím složku Home…"),
        ("Most draining — last 24 hours", "Největší spotřeba — 24 hodin"),
        ("My Tools", "Moje nástroje"),
        ("Network usage by app", "Síťový provoz podle aplikace"),
        ("No apps match", "Žádné aplikace neodpovídají"),
        ("No leaked credentials", "Žádné uniklé přihlašovací údaje"),
        ("Nothing to clean here", "Tady není co uklízet"),
        ("Nothing to remove", "Není co odstranit"),
        ("Nothing reclaimed yet", "Zatím nic uvolněno"),
        ("Orphaned launch agents", "Osiřelí launch agenti"),
        ("Reading privacy grants…", "Načítám oprávnění…"),
        ("Reading your applications…", "Načítám aplikace…"),
        ("Recommendations", "Doporučení"),
        ("Scan for threats", "Sken hrozeb"),
        ("Scan your Home folder", "Naskenovat složku Home"),
        ("Scanning for leaked secrets…", "Skenuji uniklé tajné údaje…"),
        ("Scanning for threats…", "Skenuji hrozby…"),
        ("Secrets scanner", "Skener tajných údajů"),
        ("Starts at login", "Spouští se při přihlášení"),
        ("Storage map", "Mapa místa"),
        ("Storage reclaimed", "Uvolněné místo"),
        ("Storage trend", "Trend místa"),
        ("System extensions", "Systémová rozšíření"),
        ("Try a different search.", "Zkus jiné hledání."),
        ("Updates available", "Dostupné aktualizace"),
        ("Vault is empty", "Trezor je prázdný"),
        ("By category", "Podle kategorie"),
        ("Scan for reclaimable space", "Hledat uvolnitelné místo"),
        ("or drop a folder anywhere here", "nebo sem přetáhni složku"),
        ("reclaimable", "uvolnitelných"),
        ("items", "položek"),
        ("Move to Vault", "Přesunout do trezoru"),
        ("Include in cleanup", "Zahrnout do úklidu"),
        ("AI second opinion", "AI druhý názor"),
        ("AI cleanup plan", "AI plán úklidu"),
        ("Largest files", "Největší soubory"),
        ("Messages Attachments", "Přílohy ze Zpráv"),
        ("Photos/videos received in Messages", "Fotky/videa přijaté ve Zprávách"),
        ("iOS backups", "iOS zálohy"),
        ("System tweaks", "Systémové tweaky"),
        ("Reversible power-user settings. Each toggle says exactly what it writes and records its prior value, so it can be turned back off to precisely how it was.", "Vratná pokročilá nastavení. Každý přepínač přesně říká, co zapisuje, a uloží předchozí hodnotu, takže ho lze vrátit přesně do původního stavu."),
        ("Show hidden files in Finder", "Zobrazit skryté soubory ve Finderu"),
        ("Show all file extensions", "Zobrazit všechny přípony souborů"),
        ("Show Finder path bar", "Zobrazit lištu cesty ve Finderu"),
        ("No .DS_Store on network shares", "Žádné .DS_Store na síťových discích"),
        ("Screenshots as PNG", "Screenshoty jako PNG"),
        ("No window shadow in screenshots", "Bez stínu okna ve screenshotech"),
        ("Extensions & add-ons", "Rozšíření a doplňky"),
        ("Quick Look plugins, preference panes, screen savers, Audio Units and more that accumulate in your Library. Read-only — reveal in Finder to remove.", "Quick Look pluginy, prefpanes, spořiče, Audio Units a další, co se hromadí v Library. Jen ke čtení — pro odebrání zobraz ve Finderu."),
        ("Scanning add-ons…", "Skenuji doplňky…"),
        ("Scan to list your installed add-ons.", "Skenem zobrazíš nainstalované doplňky."),
        ("system", "systém"),
        ("Quick Look", "Quick Look"),
        ("Preference Pane", "Předvolby (panel)"),
        ("Screen Saver", "Spořič obrazovky"),
        ("Internet Plug-In", "Internetový plugin"),
        ("Audio Unit", "Audio Unit"),
        ("Spotlight Importer", "Spotlight importér"),
        ("Color Picker", "Výběr barvy"),
        ("Dormant projects", "Spící projekty"),
        ("Regenerable build junk (node_modules, target, DerivedData…) grouped by git repo and how long since its last commit — reclaim from projects you haven't touched in months, with confidence.", "Znovu-generovatelný build balast (node_modules, target, DerivedData…) seskupený podle git repa a stáří posledního commitu — s jistotou uvolni místo z projektů, kterých ses měsíce nedotkl."),
        ("Scanning projects…", "Skenuji projekty…"),
        ("days since last commit", "dní od posledního commitu"),
        ("no git history", "bez git historie"),
        ("Reclaim", "Uvolnit"),
        ("Local iPhone/iPad backups, oldest first — often the biggest reclaim on a Mac. This may be your only backup, so removal is per-item and goes to the vault (undoable).", "Lokální zálohy iPhonu/iPadu, od nejstarší — často největší uvolnění místa na Macu. Může to být tvá jediná záloha, proto se maže po jedné a jde do trezoru (vratně)."),
        ("Scan to list local device backups.", "Skenem zobrazíš lokální zálohy zařízení."),
        ("last backup", "poslední záloha"),
        ("date unknown", "datum neznámé"),
        ("backup to the vault?", "zálohu do trezoru?"),
        ("It moves to the reversible vault (undoable until purge). If this is your only backup of that device, make sure you have another.", "Přesune se do vratného trezoru (vratné do vyprázdnění). Pokud je to tvá jediná záloha toho zařízení, ujisti se, že máš jinou."),
        ("The biggest individual files in your Home — a fast way to find single space hogs. Review-only: each moves to the vault (undoable) only when you choose.", "Největší jednotlivé soubory v tvém Home — rychlý způsob, jak najít žrouty místa. Jen k prohlédnutí: každý se do trezoru (vratně) přesune, až když si vybereš."),
        ("Scanning for large files…", "Hledám velké soubory…"),
        ("Scan to list the biggest files taking up space.", "Skenem zobrazíš největší soubory, co zabírají místo."),
        ("file(s)", "souborů"),
        ("Select the safe stuff", "Vybrat bezpečné"),
        ("pre-checks only regenerable items — review below, then Move to Vault", "předvybere jen znovu-generovatelné položky — zkontroluj níže, pak Přesunout do trezoru"),
        ("on-device", "na zařízení"),
        ("Automatic", "Automaticky"),
        ("Local", "Lokální"),
        ("Gemini", "Gemini"),
        ("AI assistant", "AI asistent"),
        ("Which AI answers", "Která AI odpovídá"),
        ("Automatic prefers a local model (offline) and falls back to Gemini. Or force one.", "Automaticky preferuje lokální model (offline) a jako zálohu použije Gemini. Nebo si vynuť jeden."),
        ("Now answering:", "Teď odpovídá:"),
        ("Local model (Ollama)", "Lokální model (Ollama)"),
        ("Running", "Běží"),
        ("Not detected — set it up in the Assistant tab.", "Nedetekováno — nastav v záložce Asistent."),
        ("Gemini (cloud, opt-in)", "Gemini (cloud, volitelné)"),
        ("API key found — metadata only, never file contents.", "API klíč nalezen — jen metadata, nikdy obsah souborů."),
        ("Add an API key to enable. Metadata only, never file contents.", "Přidej API klíč pro zapnutí. Jen metadata, nikdy obsah souborů."),
        ("Switch which AI answers: Automatic, Local (Ollama, offline) or Gemini (cloud).", "Přepni, která AI odpovídá: Automaticky, Lokální (Ollama, offline) nebo Gemini (cloud)."),
        ("Describe a rule", "Popiš pravidlo"),
        ("e.g. delete screenshots older than 30 days", "např. smaž screenshoty starší 30 dní"),
        ("Suggest", "Navrhnout"),
        ("Couldn't turn that into a rule. Try something like “delete screenshots older than 30 days”.", "Nepodařilo se z toho udělat pravidlo. Zkus třeba „smaž screenshoty starší 30 dní“."),
        ("Proposed rule — review before adding", "Navržené pravidlo — zkontroluj před přidáním"),
        ("Using a stronger local model for more accurate rules.", "Používám silnější lokální model pro přesnější pravidla."),
        ("larger than", "větší než"),
        ("name contains", "název obsahuje"),
        ("Uninstall selected", "Odinstalovat vybrané"),
        ("Includes this app's settings — Undo restores it fully configured, not just the bare app.", "Zahrnuje i nastavení této aplikace — Undo ji obnoví plně nakonfigurovanou, ne jen holou aplikaci."),
        ("selected", "vybráno"),
        ("Search applications…", "Hledat aplikace…"),
        ("This category is already tidy in", "V této složce už je uklizeno:"),
        ("Nothing to restore — the vault copies were already gone.", "Není co obnovit — kopie v trezoru už tam nebyly."),
        // Energy
        ("Charging", "Nabíjí se"),
        ("On battery", "Na baterii"),
        ("About", "Asi"),
        ("until full", "do plného nabití"),
        ("remaining", "zbývá"),
        ("Health", "Kondice"),
        ("Cycles", "Cykly"),
        ("Temp", "Teplota"),
        ("Freeing…", "Uvolňuji…"),
        ("Free up memory", "Uvolnit paměť"),
        ("Runs macOS purge to free inactive memory — non-destructive", "Spustí macOS purge pro uvolnění neaktivní paměti — nedestruktivní"),
        ("of", "z"),
        ("App", "Aplikace"),
        ("Wired", "Rezervováno"),
        ("Compressed", "Komprimováno"),
        ("Free", "Volné"),
        ("Reading energy usage…", "Načítám spotřebu energie…"),
        ("Why is this using power?", "Proč to spotřebovává energii?"),
        ("Measuring per-app traffic…", "Měřím provoz podle aplikace…"),
        ("Cumulative traffic since each process started (via nettop). Read-only.", "Kumulativní provoz od spuštění procesu (přes nettop). Jen ke čtení."),
        ("Building history… this fills in while Kestrel is running.", "Sbírám historii… doplní se, dokud Kestrel běží."),
        ("Recorded since", "Zaznamenáno od"),
        ("Quit", "Ukončit"),
        ("This asks the app to quit (SIGTERM). Unsaved work in that app may be lost.", "Požádá aplikaci o ukončení (SIGTERM). Neuložená práce může být ztracena."),

        // Security
        ("macOS protection is on", "Ochrana macOS je zapnutá"),
        ("Protection needs a look", "Ochrana potřebuje pozornost"),
        ("Gatekeeper and XProtect are active.", "Gatekeeper a XProtect jsou aktivní."),
        ("One of macOS's built-in defenses is off.", "Jedna z vestavěných ochran macOS je vypnutá."),
        ("On", "Zap"),
        ("Off", "Vyp"),
        ("Unknown", "Neznámé"),
        ("Scan for malware", "Skenovat malware"),
        ("Reading files in", "Čtu soubory v"),
        ("No threats", "Bez hrozeb"),
        ("Scanned", "Naskenováno"),
        ("file(s) — no threats found. No scare tactics.", "souborů — žádné hrozby. Žádné strašení."),
        ("finding(s), each with evidence", "nálezů, každý s důkazem"),
        ("These agents point at programs that no longer exist — usually safe to remove.", "Tito agenti míří na programy, které už neexistují — obvykle bezpečné odstranit."),
        ("Came from the internet", "Staženo z internetu"),
        ("Files in Downloads still flagged by Gatekeeper (quarantine) — normal for anything you downloaded. The agent shows what fetched it.", "Soubory ve Stažených stále označené Gatekeeperem (karanténa) — normální u čehokoli staženého. Agent ukazuje, co je stáhlo."),

        // Tools
        ("Trash Bins", "Koše"),
        ("Empty every Trash — undoable via the vault", "Vysypat všechny koše — vratné přes trezor"),
        ("App Leftovers", "Zbytky aplikací"),
        ("Data left behind by removed apps", "Data po odstraněných aplikacích"),
        ("Old Installers", "Staré instalátory"),
        (".dmg / .pkg / .iso in Downloads", ".dmg / .pkg / .iso ve Stažených"),
        ("Screenshots", "Snímky obrazovky"),
        ("Screenshots on the Desktop", "Snímky obrazovky na ploše"),
        ("Downloads", "Stažené"),
        ("Files older than 30 days", "Soubory starší 30 dní"),
        ("Mail Attachments", "Přílohy e-mailů"),
        ("Locally cached, re-downloadable", "Lokální kopie, znovu stažitelné"),
        ("Similar Images", "Podobné obrázky"),
        ("Keep the best of each group", "Ponechat nejlepší z každé skupiny"),
        ("Scan all", "Skenovat vše"),
        ("Cloud Cleanup (iCloud)", "Cloud úklid (iCloud)"),
        ("Large files iCloud keeps a local copy of — offload to free space; they stay in iCloud.", "Velké soubory, u kterých iCloud drží lokální kopii — offloadem uvolníš místo; v iCloudu zůstanou."),
        ("Scanning iCloud Drive…", "Skenuji iCloud Drive…"),
        ("Scan to find large local iCloud copies you can offload.", "Skenuj a najdi velké lokální iCloud kopie k offloadu."),
        ("Offload", "Offload"),
        ("Scan", "Skenovat"),
        ("Activity report", "Report aktivity"),
        ("Export report (.md)", "Exportovat report (.md)"),
        ("action(s)", "akcí"),
        ("When", "Kdy"),
        ("Action", "Akce"),
        ("Item", "Položka"),
        ("Generated locally by Kestrel — nothing left this Mac.", "Vygenerováno lokálně Kestrelem — nic neopustilo tento Mac."),
        ("Storage hotspots", "Žrouti místa"),
        ("The folders most likely to balloon, measured daily. A ↑ shows what grew since the last check — all regeneratable.", "Složky, které nejspíš bobtnají, měřené denně. Šipka ↑ ukazuje, co narostlo od minula — vše znovu-generovatelné."),
        ("Xcode DerivedData", "Xcode DerivedData"),
        ("Xcode device support", "Xcode device support"),
        ("iOS backups", "Zálohy iOS"),
        ("Trash", "Koš"),
        ("Drive health", "Zdraví disku"),
        ("Verified", "V pořádku"),
        ("Failing — back up now", "Selhává — zálohuj hned"),
        ("Finds look-alike photos in your Pictures. The best of each group is kept; tap a photo to change what moves to the vault.", "Najde podobné fotky ve složce Obrázky. Nejlepší z každé skupiny se nechá; klepnutím na fotku změníš, co půjde do trezoru."),
        ("Scanning your photos…", "Prohledávám fotky…"),
        ("Scan to find similar or duplicate photos you can thin out.", "Skenuj a najdi podobné či duplicitní fotky k pročištění."),
        ("group(s)", "skupin"),
        ("Moving…", "Přesouvám…"),
        ("more group(s)", "dalších skupin"),
        ("Best", "Nejlepší"),
        ("No similar photos found.", "Žádné podobné fotky nenalezeny."),
        ("Duplicate Files", "Duplicitní soubory"),
        ("Dedupe (APFS)", "Deduplikovat (APFS)"),
        ("Reclaim the space but keep both files — they share storage until edited.", "Uvolní místo, ale nechá oba soubory — sdílí úložiště, dokud jeden neupravíš."),
        ("Byte-identical files in a folder you pick. One copy is kept; tap any file to change what moves to the vault.", "Bajt po bajtu shodné soubory ve vybrané složce. Jedna kopie se nechá; klepnutím na soubor změníš, co půjde do trezoru."),
        ("Hashing files…", "Počítám hashe…"),
        ("Scan the folder to find exact duplicates you can remove.", "Prohledej složku a najdi přesné duplicity k odstranění."),
        ("Keep", "Nechat"),
        ("No duplicate files found.", "Žádné duplicitní soubory nenalezeny."),
        ("Developer caches", "Vývojářské cache"),
        ("Global caches of npm, pip, Homebrew, Gradle, Cargo, Go, CocoaPods, DerivedData and more — all rebuilt on demand, so clearing them only costs a re-download.", "Globální cache npm, pip, Homebrew, Gradle, Cargo, Go, CocoaPods, DerivedData a dalších — vše se znovu sestaví na vyžádání, takže vyčištění stojí jen opětovné stažení."),
        ("Measuring developer caches…", "Měřím vývojářské cache…"),
        ("Scan to size up your package-manager and build caches.", "Skenuj a zjisti velikost cache balíčkovačů a buildů."),
        ("cache(s)", "cache"),
        ("No developer caches found.", "Žádné vývojářské cache nenalezeny."),
        ("Browser caches, history and cookies. Nothing is preselected — clearing history signs you out of sites. Passwords and bookmarks are never touched.", "Cache prohlížečů, historie a cookies. Nic není předvybráno — smazání historie tě odhlásí ze stránek. Hesel ani záložek se to nikdy nedotkne."),
        ("Looking for browser data…", "Hledám data prohlížečů…"),
        ("Scan to find browsing traces you can clear.", "Skenuj a najdi stopy prohlížení k vyčištění."),
        ("Clearing…", "Čistím…"),
        ("No browser data found.", "Žádná data prohlížečů nenalezena."),
        ("cache", "cache"),
        ("history", "historie"),
        ("cookies", "cookies"),
        ("Safe — just re-downloaded as you browse.", "Bezpečné — znovu se stáhne při prohlížení."),
        ("Clears your browsing history.", "Smaže tvou historii prohlížení."),
        ("Signs you out of websites.", "Odhlásí tě z webových stránek."),
        ("Include this file", "Zahrnout tento soubor"),
        ("vault", "trezoru"),
        ("Memory unavailable.", "Paměť není dostupná."),
        ("No battery.", "Bez baterie."),
        ("Recent load", "Nedávná zátěž"),
        ("Uptime", "Doba běhu"),
        ("Top Consumers", "Největší žrouti"),
        ("Reading…", "Načítám…"),
        ("Wi-Fi connection", "Wi-Fi připojení"),
        ("Test your connection", "Otestuj své připojení"),
        ("Volumes", "Svazky"),
        ("Run a cleanup and what you free up appears here.", "Spusť úklid a co uvolníš, se objeví tady."),
        ("A daily snapshot builds this over a couple of days.", "Denní snímek to za pár dní postaví."),
        ("Empty — cleaned items land here, restorable until you purge.", "Prázdné — uklizené položky přistanou tady, obnovitelné, dokud je nevyprázdníš."),
        ("Running Smart Care…", "Spouštím Smart Care…"),
        ("Working…", "Pracuji…"),
        ("Time Machine", "Stroj času"),
        ("Walk back any cleanup — restore a whole session or a single file", "Vrať jakýkoli úklid — obnov celou relaci nebo jediný soubor"),
        ("Reading the vault…", "Čtu trezor…"),
        ("Gathering every cleanup you can undo.", "Sbírám všechny úklidy, které jde vrátit."),
        ("Nothing to restore yet", "Zatím není co obnovit"),
        ("Everything a cleanup removes lands here, fully reversible until you purge it.", "Vše, co úklid odstraní, přistane tady — plně vratné, dokud to nevyprázdníš."),
        ("No matches", "Žádné shody"),
        ("No cleaned items match your filter.", "Filtru neodpovídají žádné uklizené položky."),
        ("restorable", "k obnovení"),
        ("cleanup(s)", "úklidů"),
        ("Reveal vault", "Zobrazit trezor"),
        ("Last 7 days", "Posledních 7 dní"),
        ("Last 30 days", "Posledních 30 dní"),
        ("All time", "Za celou dobu"),
        ("Search restored files…", "Hledat v uklizených souborech…"),
        ("Restore all", "Obnovit vše"),
        ("more", "dalších"),
        ("Restore this file", "Obnovit tento soubor"),
        ("file", "soubor"),
        ("already in place", "již na místě"),
        ("failed", "selhalo"),
        ("Restore failed.", "Obnovení selhalo."),
        ("App updates", "Aktualizace aplikací"),
        ("Malware scan", "Sken malwaru"),
        ("Pick the checks below, then run them in one honest pass.", "Vyber kontroly níže a spusť je jedním poctivým průchodem."),
        ("Skipped", "Přeskočeno"),
        ("Up to date", "Aktuální"),
        ("Every Homebrew app is current", "Všechny Homebrew aplikace jsou aktuální"),
        ("app(s) have a newer version", "aplikací má novější verzi"),
        ("What's affecting your score", "Co ovlivňuje tvé skóre"),
        ("Free space", "Uvolnit místo"),
        ("See Energy", "Zobrazit Energii"),
        ("Free RAM", "Uvolnit RAM"),
        ("Couldn't free memory — it needs your permission.", "Paměť nešlo uvolnit — potřebuje to tvé oprávnění."),
        ("Freed", "Uvolněno"),
        ("of memory", "paměti"),
        ("Memory is already lean — little to free right now.", "Paměť je už štíhlá — teď není moc co uvolnit."),
        ("Empty Trash", "Vysypat koš"),
        ("Trash is already empty.", "Koš je už prázdný."),
        ("Emptied Trash —", "Koš vysypán —"),
        ("Couldn't empty the Trash.", "Koš se nepodařilo vysypat."),
        ("Exclusions", "Vyloučení"),
        ("Paths on this list are never moved or deleted — Kestrel's SafetyGuard treats them (and everything inside them) as off-limits across every module.", "Cesty na tomto seznamu se nikdy nepřesouvají ani nemažou — SafetyGuard je (i vše uvnitř) považuje za nedotknutelné napříč všemi moduly."),
        ("Nothing excluded yet. Add a folder or file you want Kestrel to always leave alone.", "Zatím nic vyloučeno. Přidej složku nebo soubor, kterých se má Kestrel vždy vyvarovat."),
        ("Add…", "Přidat…"),
        ("Exclude", "Vyloučit"),
        ("Remove", "Odebrat"),
        ("Security posture", "Stav ochrany"),
        ("Ransomware canary", "Ransomware kanárek"),
        ("App signatures", "Podpisy aplikací"),
        ("Week in review", "Týden v kostce"),
        ("Narrate", "Vyprávěj"),
        ("A short, honest recap of what changed on your Mac — generated locally, nothing leaves the device.", "Krátké čestné shrnutí, co se na Macu změnilo — generováno lokálně, nic neopustí zařízení."),
        ("Network connections", "Síťová spojení"),
        ("Listening ports", "Naslouchající porty"),
        ("What's listening on local TCP ports right now — handy for finding a stray dev server. Read-only; Kestrel never kills anything.", "Co teď naslouchá na lokálních TCP portech — hodí se na dohledání zapomenutého dev serveru. Jen ke čtení; Kestrel nic nezabíjí."),
        ("Check to see what's listening.", "Klepnutím zobrazíš, co naslouchá."),
        ("Checking…", "Kontroluji…"),
        ("Which apps have an open outbound connection right now, and to where. Read-only — Kestrel reports, it never blocks.", "Které aplikace mají teď otevřené odchozí spojení a kam. Jen ke čtení — Kestrel informuje, nikdy neblokuje."),
        ("Check to see current outbound connections.", "Klepnutím zobrazíš aktuální odchozí spojení."),
        ("Inspecting app signatures…", "Kontroluji podpisy aplikací…"),
        ("No applications found to inspect.", "Nenalezeny žádné aplikace ke kontrole."),
        ("apps inspected — every signature verifies.", "aplikací zkontrolováno — každý podpis sedí."),
        ("app(s) whose signature doesn't verify — may have been modified after signing:", "aplikací, jejichž podpis nesedí — možná byly po podepsání upraveny:"),
        ("Developer ID", "Developer ID"),
        ("App Store", "App Store"),
        ("Ad-hoc", "Ad-hoc"),
        ("Unsigned", "Nepodepsáno"),
        ("Invalid signature", "Neplatný podpis"),
        ("Kestrel: possible ransomware", "Kestrel: možný ransomware"),
        ("Kestrel weekly digest", "Kestrel týdenní souhrn"),
        ("Your weekly Kestrel summary is ready.", "Tvůj týdenní souhrn Kestrelu je připravený."),
        ("reclaimed", "uvolněno"),
        ("day", "den"),
        ("Local notifications", "Lokální notifikace"),
        ("Local alerts: low disk space, a weekly digest, and ransomware-canary trips. Nothing leaves this Mac.", "Lokální upozornění: docházející místo, týdenní souhrn a spuštění ransomware kanárka. Nic neopustí tento Mac."),
        ("Decoy files changed unexpectedly — something may be encrypting your files. Open Kestrel → Security.", "Návnadové soubory se nečekaně změnily — něco možná šifruje tvoje soubory. Otevři Kestrel → Security."),
        ("Armed", "Aktivní"),
        ("Tampered!", "Napadeno!"),
        ("Arm protection", "Aktivovat ochranu"),
        ("Disarm", "Deaktivovat"),
        ("Check now", "Zkontrolovat teď"),
        ("Kestrel plants harmless decoy files in Documents, Desktop and Pictures and watches them. If something rewrites or deletes them — a hallmark of ransomware — you get warned. Detection only: Kestrel never deletes or changes your files.", "Kestrel nastraží neškodné návnadové soubory do Dokumentů, na Plochu a do Obrázků a hlídá je. Když je něco přepíše nebo smaže — typický projev ransomwaru — dostaneš varování. Jen detekce: Kestrel nikdy tvoje soubory nemaže ani nemění."),
        ("Decoy files changed unexpectedly — something may be modifying your files. Consider disconnecting from the network and checking recent activity.", "Návnadové soubory se nečekaně změnily — něco možná upravuje tvoje soubory. Zvaž odpojení od sítě a zkontroluj nedávnou aktivitu."),
        ("decoy(s) intact — no sign of mass file tampering.", "návnad v pořádku — žádná známka hromadné manipulace se soubory."),
        ("deleted", "smazáno"),
        ("modified", "změněno"),
        ("Your Mac's built-in protections, read straight from the system. Facts only — SIP off is normal on some developer setups.", "Vestavěné ochrany tvého Macu, načtené přímo ze systému. Jen fakta — vypnuté SIP je u některých vývojářských sestav normální."),
        ("Stealth mode", "Skrytý režim"),
        ("The request failed — try again.", "Požadavek selhal — zkus to znovu."),
        ("The assistant didn't respond. Check its setup in Settings and your connection.", "Asistent neodpověděl. Zkontroluj jeho nastavení v Nastavení a připojení."),
        ("Best option (free & offline): install Ollama and pull a model — nothing leaves your Mac, no API key.", "Nejlepší volba (zdarma & offline): nainstaluj Ollamu a stáhni model — nic neopustí tvůj Mac, žádný API klíč."),
        ("Best option (free & offline): run a local AI with Ollama — nothing leaves your Mac, no API key, no account.", "Nejlepší volba (zdarma & offline): lokální AI přes Ollamu — nic neopustí tvůj Mac, žádný API klíč, žádný účet."),
        ("1. Install Ollama (a small free app). 2. Come back — Kestrel finds it and offers the model.", "1. Nainstaluj Ollamu (malá appka zdarma). 2. Vrať se — Kestrel ji najde a nabídne model."),
        ("Install Ollama", "Nainstalovat Ollamu"),
        ("Prefer the terminal? Run:", "Radši terminál? Spusť:"),
        ("Ollama is installed. Download the recommended model", "Ollama je nainstalovaná. Stáhni doporučený model"),
        ("and the assistant turns on.", "a asistent se zapne."),
        ("Downloading", "Stahuji"),
        ("Downloading…", "Stahuji…"),
        ("Download AI model", "Stáhnout AI model"),
        ("Starting…", "Spouštím…"),
        ("Couldn't start the download — is Ollama running?", "Nepodařilo se spustit stahování — běží Ollama?"),
        ("Download failed — check your connection and that Ollama is running.", "Stahování selhalo — zkontroluj připojení a jestli běží Ollama."),
        ("Or use Google Gemini (cloud) — put your API key in this file:", "Nebo použij Google Gemini (cloud) — vlož svůj API klíč do tohoto souboru:"),
        ("Either way it sends only metadata (names, sizes, categories) — never file contents.", "Tak jako tak posílá jen metadata (názvy, velikosti, kategorie) — nikdy obsah souborů."),
        ("On-device (offline)", "V zařízení (offline)"),
        ("Gemini (cloud)", "Gemini (cloud)"),
        ("Off", "Vypnuto"),
        ("Honest AI help · fully on-device, nothing leaves your Mac", "Čestná AI pomoc · plně v zařízení, nic neopustí tvůj Mac"),
        ("Best option: turn on Apple Intelligence in System Settings — Kestrel then runs the assistant fully on-device, with no key and nothing leaving your Mac.", "Nejlepší volba: zapni Apple Intelligence v Nastavení systému — Kestrel pak spustí asistenta plně v zařízení, bez klíče a nic neopustí tvůj Mac."),
        ("Or, to use Google Gemini instead, put your API key in a file:", "Nebo, pokud chceš raději Google Gemini, vlož svůj API klíč do souboru:"),
        ("By app", "Podle aplikace"),
        ("By permission", "Podle oprávnění"),
        ("Search permissions…", "Hledat oprávnění…"),
        ("sensitive", "citlivé"),
        ("Manage in System Settings", "Spravovat v Nastavení systému"),
        ("Holds camera, microphone, screen, input or full-disk access", "Má přístup ke kameře, mikrofonu, obrazovce, vstupu nebo celému disku"),
        ("Hardening", "Zpevnění"),
        ("Fix", "Opravit"),
        ("One-tap jumps to each setting. Kestrel reads your posture but never flips a system switch behind your back.", "Jedním klepnutím skočíš na dané nastavení. Kestrel čte stav ochran, ale nikdy nepřepne systémový přepínač za tvými zády."),
        ("Your Mac is well hardened — nothing to change.", "Tvůj Mac je dobře zabezpečený — není co měnit."),
        ("Turn on FileVault", "Zapnout FileVault"),
        ("Encrypts your disk so a lost or stolen Mac can't be read.", "Zašifruje disk, takže ztracený nebo ukradený Mac nikdo nepřečte."),
        ("Turn on the firewall", "Zapnout firewall"),
        ("Blocks unsolicited incoming network connections.", "Blokuje nevyžádaná příchozí síťová spojení."),
        ("Enable automatic updates", "Zapnout automatické aktualizace"),
        ("Security fixes install as soon as Apple ships them.", "Bezpečnostní záplaty se nainstalují hned, jak je Apple vydá."),
        ("Disable the guest account", "Vypnout účet hosta"),
        ("A guest login is one more way in — turn it off if you don't use it.", "Účet hosta je další cesta dovnitř — vypni ho, když ho nepoužíváš."),
        ("Keep Gatekeeper on", "Nechat Gatekeeper zapnutý"),
        ("Stops unsigned, unnotarized apps from launching by accident.", "Zabrání omylem spustit nepodepsané a nenotarizované aplikace."),
        ("Updates", "Aktualizace"),
        ("Current version", "Aktuální verze"),
        ("Check now", "Zkontrolovat teď"),
        ("Checking…", "Kontroluji…"),
        ("Check for updates automatically", "Automaticky kontrolovat aktualizace"),
        ("On launch, Kestrel asks GitHub for the latest release — the only automatic network request. It sends no data.", "Při spuštění se Kestrel zeptá GitHubu na nejnovější verzi — jediný automatický síťový požadavek. Neposílá žádná data."),
        ("is available", "je k dispozici"),
        ("You have", "Máš"),
        ("Release notes", "Poznámky k vydání"),
        ("Download", "Stáhnout"),
        ("Downloading…", "Stahuji…"),
        ("You're on the latest version.", "Máš nejnovější verzi."),
        ("Couldn't reach GitHub to check for updates.", "Nepodařilo se spojit s GitHubem pro kontrolu aktualizací."),
        ("Downloaded to your Downloads folder — open it and drag Kestrel to Applications.", "Staženo do složky Stažené — otevři a přetáhni Kestrel do Aplikací."),
        ("Download failed. Opening the release page instead.", "Stažení selhalo. Otevírám raději stránku vydání."),
        ("No launch agents found.", "Žádní launch agenti nenalezeni."),
        ("Launch agents that run when you log in. Ones pointing at a missing program are flagged.", "Launch agenti spouštění při přihlášení. Ti mířící na chybějící program jsou označeni."),
        ("Scan for leaked credentials", "Skenovat uniklé údaje"),
        ("Reading", "Čtu"),
        ("No API keys, tokens or private keys found in", "Žádné API klíče, tokeny ani privátní klíče v"),
        ("potential secret(s)", "možných tajných údajů"),
        ("Nothing is preventing sleep.", "Nic nebrání uspání."),
        ("Advisory — run these yourself; they change system state. Copy the command when you're ready.", "Doporučující — spusť sám; mění stav systému. Zkopíruj příkaz, až budeš připraven."),

        // Applications
        ("From Homebrew casks — advisory; Kestrel never updates silently.", "Z Homebrew casks — doporučující; Kestrel nikdy neaktualizuje potají."),
        ("app(s)", "aplikací"),
        ("apps", "aplikací"),
        ("Nothing was found to", "Nebylo co"),
        ("reset", "resetovat"),
        ("remove", "odstranit"),
        ("These", "Těchto"),
        ("item(s) —", "položek —"),
        ("— will move to the vault. Undoable.", "— se přesune do trezoru. Vratné."),
        ("Close", "Zavřít"),
        ("Select for batch uninstall", "Vybrat pro hromadné odinstalování"),
        ("Reveal in Finder", "Zobrazit ve Finderu"),
        ("Name", "Název"),
        ("Size", "Velikost"),
        ("Last used", "Naposledy použito"),
        ("Oldest first", "Nejstarší první"),
        ("total", "celkem"),
        ("Sort", "Řadit"),
        ("apps unused for 90+ days", "aplikací nepoužitých 90+ dní"),
        ("— review and uninstall the ones you don't need.", "— projdi a odinstaluj ty, co nepotřebuješ."),
        ("Show oldest", "Ukázat nejstarší"),
        ("unused", "nepoužito"),

        // Permissions — TCC service friendly names
        ("Camera", "Kamera"),
        ("Microphone", "Mikrofon"),
        ("Full Disk Access", "Plný přístup k disku"),
        ("Desktop folder", "Složka Plocha"),
        ("Documents folder", "Složka Dokumenty"),
        ("Downloads folder", "Složka Stažené"),
        ("Network volumes", "Síťové svazky"),
        ("Removable volumes", "Vyměnitelné svazky"),
        ("Accessibility", "Zpřístupnění"),
        ("Input monitoring", "Sledování vstupu"),
        ("Screen recording", "Nahrávání obrazovky"),
        ("Automation", "Automatizace"),
        ("Photos", "Fotky"),
        ("Contacts", "Kontakty"),
        ("Calendar", "Kalendář"),
        ("Reminders", "Připomínky"),
        ("Location", "Poloha"),
        ("Media library", "Knihovna médií"),
        ("Speech recognition", "Rozpoznávání řeči"),

        // Permissions
        ("Per-user privacy grants, read-only from your TCC database. System-level ones like Full Disk Access and Accessibility live in a root-only database and may not all appear here — manage everything in System Settings.", "Oprávnění na úrovni uživatele, jen ke čtení z tvé TCC databáze. Systémová jako plný přístup k disku a zpřístupnění žijí v databázi jen pro root a nemusí se tu všechna zobrazit — spravuj vše v Nastavení systému."),
        ("No app permissions found", "Žádná oprávnění aplikací"),
        ("Full Disk Access needed", "Potřeba plný přístup k disku"),
        ("Nothing has requested a protected resource yet.", "Zatím nic nežádalo o chráněný zdroj."),
        ("Grant Kestrel Full Disk Access to read the privacy database.", "Udělte Kestrelu plný přístup k disku pro čtení databáze soukromí."),

        // Smart Care results
        ("Here's what it found — nothing was deleted.", "Tady je, co našel — nic nebylo smazáno."),
        ("Reclaimable space, macOS protection and a Downloads malware scan, in one honest pass.", "Uvolnitelné místo, ochrana macOS a sken malwaru ve Stažených — v jednom poctivém průchodu."),
        ("Check", "Zkontroluj"),
        ("Gatekeeper + XProtect active", "Gatekeeper + XProtect aktivní"),
        ("A defense is off", "Ochrana je vypnutá"),
        ("files", "souborů"),
        ("finding(s) with evidence", "nálezů s důkazem"),
        ("Nothing to reclaim", "Není co uvolnit"),
        ("Your Home folder is already tidy.", "Tvoje složka Home je už uklizená."),
        ("safe item(s) across caches, logs and dev artifacts.", "bezpečných položek napříč cache, logy a dev artefakty."),

        // Space
        ("Scan Home", "Naskenovat Home"),
        ("Rescan", "Znovu skenovat"),
        ("Reading top-level folders…", "Čtu složky nejvyšší úrovně…"),
        ("Sized by real on-disk usage (allocated bytes), so sparse files like Docker.raw show their true footprint. Click a block to drill in.", "Velikost podle reálného využití disku (alokované bajty), takže řídké soubory jako Docker.raw ukazují skutečnou stopu. Klikni na blok pro zanoření."),
        ("Used", "Využito"),
        ("Purgeable", "Uvolnitelné"),
        ("This reads Desktop, Documents, Downloads and Pictures, so macOS may ask for permission. Click Scan Home when you're ready.", "Čte Plochu, Dokumenty, Stažené a Obrázky, takže macOS může požádat o oprávnění. Klikni na Naskenovat Home, až budeš připraven."),

        // Full Disk Access banner
        ("Grant Full Disk Access", "Udělit plný přístup k disku"),
        ("Without it, macOS hides the Trash, Mail and some caches — so tools like “Empty Trash” find nothing. Turn Kestrel on in Settings, then relaunch.", "Bez něj macOS skryje Koš, Mail a některé cache — takže nástroje jako Vysypat koš nic nenajdou. Zapni Kestrel v Nastavení a spusť znovu."),
        ("Open Full Disk Access settings", "Otevřít nastavení plného přístupu k disku"),

        // Settings
        ("Audit log", "Auditní log"),
        ("Reveal ~/.kestrel in Finder", "Zobrazit ~/.kestrel ve Finderu"),
        ("Cleanups are dry-run by default. Nothing is deleted outright — items move to the vault and can be undone. Zero telemetry: nothing leaves this Mac.", "Úklidy jsou defaultně nanečisto. Nic se nemaže napřímo — položky jdou do trezoru a jdou vrátit. Nulová telemetrie: nic neopustí tento Mac."),
        ("session(s)", "relací"),
        ("Everything a cleanup removes is moved here first, so it can be restored. Purging is the only place data is really deleted.", "Vše, co úklid odstraní, jde nejdřív sem, aby to šlo obnovit. Protřídění je jediné místo, kde se data opravdu mažou."),
        ("Cleaned items will appear here, restorable until you purge.", "Vyčištěné položky se objeví tady, obnovitelné dokud je neprotřídíš."),
        ("Purge older than", "Protřídit starší než"),
        ("Restore", "Obnovit"),
        ("item(s)", "položek"),

        // Assistant
        ("Honest AI help · sends metadata only", "Poctivá AI pomoc · posílá jen metadata"),
        ("New chat", "Nový chat"),
        ("Ask me about your Mac's storage, or analyze a folder.", "Zeptej se na místo na Macu nebo nech analyzovat složku."),
        ("What's using most of my disk?", "Co mi zabírá nejvíc místa?"),
        ("Is it safe to clear developer caches?", "Je bezpečné smazat vývojářské cache?"),
        ("How can I free space as a developer?", "Jak jako vývojář uvolním místo?"),
        ("What are the biggest wins to reclaim space?", "Kde nejvíc uvolním místo?"),
        ("Choose a folder to analyze:", "Vyber složku k analýze:"),
        ("Analyze", "Analyzovat"),
        ("Ask anything…", "Zeptej se na cokoli…"),
        ("Turn on the assistant", "Zapnout asistenta"),
        ("The assistant is opt-in and off by default. To enable it, put your Google Gemini API key in a file:", "Asistent je volitelný a defaultně vypnutý. Zapneš ho vložením svého Google Gemini API klíče do souboru:"),
        ("It then sends only metadata (names, sizes, categories) — never file contents.", "Pak posílá jen metadata (názvy, velikosti, kategorie) — nikdy obsah souborů."),

        // Command palette
        ("Go to", "Přejít na"),
        ("Section", "Sekce"),
        ("Run speed test", "Spustit test rychlosti"),
        ("Ask the assistant", "Zeptat se asistenta"),
        ("Vault & logs", "Trezor a logy"),
        ("Search or run a command…", "Hledej nebo spusť příkaz…"),
        ("No matching commands.", "Žádné odpovídající příkazy."),
        ("run", "spustit"),
        ("dismiss", "zavřít"),
        ("command(s)", "příkazů"),

        // Menu-bar popover
        ("Everything looks healthy", "Vše vypadá zdravě"),
        ("A little attention needed", "Chce trochu pozornosti"),
        ("Dev junk, caches, duplicates & more", "Dev balast, cache, duplikáty a další"),
        ("Measuring…", "Měřím…"),
        ("Download & latency", "Stahování a odezva"),
        ("Open Kestrel", "Otevřít Kestrel"),

        // Automation
        ("Declarative cleanup rules — previewed, vault-backed, undoable", "Deklarativní pravidla úklidu — s náhledem, přes trezor, vratné"),
        ("Run rules on a schedule", "Spouštět pravidla na plán"),
        ("Installs a LaunchAgent that runs your rules automatically (into the vault).", "Nainstaluje LaunchAgent, který spouští pravidla automaticky (do trezoru)."),
        ("Every", "Každých"),
        ("d", "d"),
        ("Needs the kestrel CLI installed for the schedule to actually run.", "Pro reálné spouštění plánu je potřeba nainstalované kestrel CLI."),
        ("New rule", "Nové pravidlo"),
        ("Rule name (e.g. Old downloads)", "Název pravidla (např. Staré stažené)"),
        ("Older than", "Starší než"),
        ("older than", "starší než"),
        ("Add rule", "Přidat pravidlo"),
        ("No rules yet", "Zatím žádná pravidla"),
        ("Add a rule above — e.g. Downloads older than 30 days.", "Přidej pravidlo výše — např. Stažené starší 30 dní."),
        ("Nothing matches right now", "Teď nic neodpovídá"),
        ("Run now", "Spustit teď"),

        // Onboarding
        ("Welcome to Kestrel", "Vítej v Kestrelu"),
        ("A fast, honest Mac cleaner. Nothing is deleted outright — everything moves to a vault you can undo, and nothing ever leaves this Mac.", "Rychlý, poctivý čistič Macu. Nic se nemaže napřímo — vše jde do trezoru, který lze vrátit, a nic nikdy neopustí tento Mac."),
        ("Safe by design", "Bezpečný z principu"),
        ("Dry-run by default, vault + undo, honest reports — no scare tactics.", "Defaultně nanečisto, trezor + vrácení, poctivé reporty — žádné strašení."),
        ("Full Disk Access (optional)", "Plný přístup k disku (volitelně)"),
        ("Lets Kestrel see the Trash, Mail and some caches. Grant it in System Settings, then relaunch.", "Umožní Kestrelu vidět Koš, Mail a některé cache. Uděl v Nastavení systému a spusť znovu."),
        ("Open settings", "Otevřít nastavení"),
        ("AI assistant (optional, off)", "AI asistent (volitelný, vypnutý)"),
        ("Add a Gemini key to enable it. It only ever sends metadata — never file contents.", "Zapneš ho přidáním Gemini klíče. Posílá jen metadata — nikdy obsah souborů."),
        ("Get started", "Začít"),

        // Space treemap actions / Activity ledger / Permissions search
        ("Sized by real on-disk usage (allocated bytes), so sparse files like Docker.raw show their true footprint. Click a block to drill in. Right-click a block to reveal or move it to the vault.", "Velikost podle reálného využití disku (alokované bajty), takže řídké soubory jako Docker.raw ukazují skutečnou stopu. Klikni na blok pro zanoření, pravým tlačítkem pro zobrazení nebo přesun do trezoru."),
        ("moves to the vault (undoable). Protected locations are refused.", "přesune se do trezoru (vratné). Chráněná místa jsou odmítnuta."),
        ("Recent activity", "Nedávná aktivita"),
        ("Moved to vault", "Přesunuto do trezoru"),
        ("Restored", "Obnoveno"),
        ("Purged", "Protříděno"),
        ("Search apps…", "Hledat aplikace…"),

        // Categories
        ("CATEGORY", "KATEGORIE"),
        ("Everything safe", "Vše bezpečné"),
        ("Dev artifacts", "Dev artefakty"),
        ("Caches", "Cache"),
        ("Logs", "Logy"),
        ("Duplicates", "Duplikáty"),
        ("Large & old", "Velké a staré"),
        ("Privacy", "Soukromí"),    ]
}
